production:
    sessions:
        default:
            uri: <%= ENV['MONGOHQ_URL'] %>
            options:
                skip_version_check: true
                safe: true
development:
  sessions:
    default:
      database: mongoid
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: mongoid_test
      hosts:
        - localhost:27017

